---
#
# Put driver config in <projectdir>/.config/molecule/config.yml
#
dependency:
  name: galaxy
platforms:
  - name: instance
    image: "${IMAGE:-centos:8}"
    template: "${IMAGE:-generic-centos-8}"
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 0
    ANSIBLE_STDOUT_CALLBACK: yaml
