---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_IMAGE:-centos:8}"
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        #robotframework_package_name: robotframework
        #robotframework_package_version_spec: ""
        #robotframework_external_libraries: []
        robotframework_test_directory: "tests"
        robotframework_test_data: ["tests"]
