---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  - name: instance
    image: "${IMAGE:-centos:8}"
provisioner:
  name: ansible
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
