---
dependency:
  name: galaxy
driver:
  name: delegated
  provider:
    name: libvirt
platforms:
  - name: instance
    template: "${IMAGE:-generic-centos-8}"
provisioner:
  name: ansible
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml